### ISSUE TITLE
[feature request]: export load_workspaces function

### ISSUE THREAD

**Issue by rafcamlet** [natecraddock/workspaces.nvim#1]
Hi! Nice plugin :+1: 

Could you make `load_workspaces` function public or add to api something similar like `get_workspaces`? I started using this as section in https://github.com/sidebar-nvim/sidebar.nvim but I had to replicate that function as there is no way to get list of workspaces. Only print them. :)

**Comment by rafcamlet** [comment]
Sorry. I'm blind. :) But in my defence it was not mentioned in the readme.

**Comment by natecraddock** [comment]
No worries! I forgot to add it to the readme. It is in the workspaces.txt doc though :)

**Comment by natecraddock** [comment]
Added to readme!
