### ISSUE TITLE
Telescope integration

### ISSUE THREAD

**Issue by leoncruz** [natecraddock/workspaces.nvim#12]
Hello, thanks for the great plugin! I have a question: there is a way to execute others commands, like, rename and delete, through Telescope? I can't found anything about this on documentation

**Comment by natecraddock** [comment]
At the moment there aren't any telescope integrations other than opening a workspace. The reasoning behind this is that opening workspaces is likely the most common action, so telescope makes it more convenient. Adding, renaming, deleting workspaces is less common, so there isn't a need for a telescope integration.

I'm willing to reconsider this, especially if someone were to make a PR. At the same time, I also think the current status is perfectly fine. Does that make sense?

**Comment by leoncruz** [comment]
Yes, thanks! I have this doubt after reading the docs, if there are integrations for other commands. I'will close this issue now, thanks for you answer!
