### ISSUE TITLE
[Question] Usage of type field in the obtained list of workspaces

### ISSUE THREAD

**Issue by HuM4NoiD** [natecraddock/workspaces.nvim#24]
I did not find the discussions tab, so I apologize for raising an issue

I noticed a type field along with other relevant information in a single item from the table returned by `require("workspaces").get()`:
```
{                                                                                                                                                
    last_opened = "2023-08-18T09:56:56",
    name = "project",
    path = "/home/user/code/project/",
    type = ""
}
```

I wanted to know if this `type` field was being used by workspaces. 
If it wasn't, I'd want to:
- store additional information related to that particular workspace, for e.g. storing the language/package-manager/build-system of the project. (via some command or via the lua api)
- get the same info back and use it somewhere else in my configuration

**Comment by natecraddock** [comment]
> I did not find the discussions tab, so I apologize for raising an issue

This project is small enough that I think issues work fine, no worries!

The type field is used for the directory of workspaces support used by the `WorkspacesAddDir` command and other commands.

In the current code you could safely store a string in that field, so long as that string is not `'directory'` and everything should work fine from what I can see. But there is no guarantee that things would work in the future.

**Comment by HuM4NoiD** [comment]
How do I set that field and make sure it persists? is there a command? or a function that takes in the table structure mentioned in the op?

**Comment by natecraddock** [comment]
Thanks for bringing that up, I guess I didn't think hard enough. I'll take some time tomorrow to update the code to support this use case

**Comment by natecraddock** [comment]
@HuM4NoiD I just pushed a commit that adds two new functions `get_custom()` and `set_custom()` to get and set custom strings. Let me know if there is anything else needed!

**Comment by HuM4NoiD** [comment]
Looks good, Thanks!
