### ISSUE TITLE
(Recipe) Automatically change workspace when changing buffers

### ISSUE THREAD

**Issue by 0x0013** [natecraddock/workspaces.nvim#25]
I normally use a single neovim instance and work in different projects (workspaces) in it.

This would present an issue when switching to a different pane/buffer belonging to a different workspace. The old workspace would still remain active, so any actions (such as telescope search) would be constrained to the other workspace, unless I were to manually switch.

So I created an autocommand to do this automatically when switching buffers, unless the file is already in the current active workspace. Please consider if this would be worthwile including in the wiki.

Implementation can be seen in [my forked wiki repo](https://github.com/0x0013/workspaces.nvim-wiki/blob/master/Configuration-Recipes.md#automatically-change-workspace-when-switching-buffers).

**Comment by natecraddock** [comment]
Sorry I didn't realize the wiki was not public! I just made it public.

But I went ahead and added your suggestion to the wiki. Thank you!
