### ISSUE TITLE
¿How to refresh nvimTree with the workspaces path?

### ISSUE THREAD

**Issue by ghost** [natecraddock/workspaces.nvim#3]
Exist some way to refresh the nvimTree when I change in workspaces?

**Comment by natecraddock** [comment]
Hey! There is a command `:NvimTreeRefresh` that will refresh the tree. You could add this as an open hook

```lua
hooks = {
  open = {
    "NvimTreeRefresh",
  },
}
```
Alternatively, nvim-tree has a setting `update_cwd` that changes the tree root automatically each time the `DirChange` event occurs.

```lua
require("nvim-tree").setup({
  update_cwd = true,
})
```
Let me know if that helps!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/95452787/152902888-124d95b0-591f-4e3c-bd07-441d98275226.png)
When I switch between workspaces I get this error, but, If I disable the "NvimTreeRefresh" instead the telescope find_files, this works, thanks for your help, only I needed change that property for true, sorry for that, I am grateful.

**Comment by natecraddock** [comment]
Glad it works!

It's possible that you are lazy-loading nvim-tree and that's why the command didn't work.

**Comment by ghost** [comment]
Yes! I'm using lazy-loading, thanks for that!

**Comment by ghost** [comment]
Please add this for the wiki or readme, I think it might be useful to someone.
