### ISSUE TITLE
WorkspaceListDirs is not functioning

### ISSUE THREAD

**Issue by codymikol** [natecraddock/workspaces.nvim#30]
Hello, I'm encountering an issue when trying to use WorkspaceListDirs. A warning is presented that no workspaces are registered. I know that they are because the WorkspaceList command functions as expected.

https://github.com/natecraddock/workspaces.nvim/assets/13606342/4f7f6e36-ed1b-42e5-a115-d177406c16b2

**Comment by natecraddock** [comment]
Hey! Sorry for the confusion. Based on the workspaces you registered, I think this just may be a misunderstanding of the WorkspaceListDirs command.

If I understand right, both nvim-config and ghostty (nice to see another ghostty user 😄) are individual projects, so you added them with `:WorkspacesAdd`.

The `*Dirs` commands all work on groups of workspaces. For example, `:WorkspacesAddDir ~/dev` would register all subdirectories of `~/dev` as individual workspaces. This is an easy way to automatically track multiple workspaces. So `:WorkspacesListDirs` would list all of the directories added with that command.

This feature was added a while back by a contributor. Looking back, I think the implementation is a bit messy and could be cleaned up a bit (like better error messages). The docs also need work.

So `:WorkspacesList` will list all of your workspaces, but as far as I can tell, you don't have any "dir" workspaces, so `:WorkspacesListDirs` will not print anything.

Does that answer your question?

**Comment by codymikol** [comment]
That answers my question, thank you!
