### ISSUE TITLE
Rename problem

### ISSUE THREAD

**Issue by scippio** [natecraddock/workspaces.nvim#33]
How I can rename my workspace from something like "name" to: "newname - [category]" etc.? It can't take spaces etc...

**Comment by natecraddock** [comment]
Hey! You should be able to do this by using a backslash to escape the space when renaming a workspace.

```
:WorkspaceRename name name\ with\ spaces
```

Would rename "name" to "name with spaces"

**Comment by scippio** [comment]
It's not working... but I realized I need more sophisticated plugin, so I started write my own. You can close it here or something...  thanks :)

**Comment by natecraddock** [comment]
Interesting. It works for me. Good luck on your plugin!
