### ISSUE TITLE
Info notifications

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/workspaces.nvim#7]
After a WorkspacesAdd or WorkspacesRemove a notification indicating success, and after WorkspacesList a notification warning if there are no workspaces.

Put this behind a configuration boolean.

_Originally posted  in https://github.com/natecraddock/workspaces.nvim/issues/6#issuecomment-1039522449_

**Comment by danymat** [comment]
Originally posted on:

https://github.com/natecraddock/workspaces.nvim/commit/1b12d34518a3d4b94dba48910971c851efa59bad#commitcomment-66820237
